diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:diary_id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('edit/<int:diary_id>', views.edit, name='edit'),
    path('delete/<int:diary_id>', views.delete, name='delete'),
    path('heatmap/', views.heatmap, name='heatmap'),
    path('new/<int:user_id>', views.new_detail, name='new_detail'),
]

jukus/urls.py
from django.urls import path
from . import views

app_name = 'jukus'

urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

team_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('diaries/', include('diaries.urls')),
    path('subjects/', include('subjects.urls')),
    path('records/', include('records.urls')),
    path('lessons/', include('lessons.urls')),
    path('', include('jukus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diaries/models.py
from django.db import models
from subjects.models import Subject
from users.models import CustomUser
from django.utils.translation import gettext_lazy as _

# --------------------------------------------------
# 日誌モデルの定義
class Diary(models.Model):
    teacher = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='teacher', to_field='id')
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='student', to_field='id')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    date = models.DateTimeField(_('日付'), null=True)
    range = models.CharField(_('学習範囲'), max_length=50)
    homework = models.CharField(_('宿題'), max_length=50)
    content = models.CharField(_('内容'), max_length=100)
    remark = models.CharField(_('備考'), max_length=100)

diaries/forms.py
from django import forms
from diaries.models import Diary
from datetime import date, datetime
from users.models import CustomUser

# --------------------------------------------------
class DiaryForm(forms.ModelForm):
    def __init__( self, *args, **kwargs):
        super(DiaryForm,self).__init__(*args, **kwargs)
        self.fields['student'].queryset = CustomUser.objects.filter(job='student')

    class Meta:
        model = Diary
        
        # 送信フィールド
        fields = ('teacher',
                  'date',
                  'student',
                  'subject',
                  'content',
                  'range',
                  'homework',
                  'remark')
        
        # ラベル表示の編集
        labels = {'subject': '科目コース',
                  'student': '生徒',}
        
        # タグの属性
        widgets = {'range': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   'subject': forms.Select(attrs={'class': 'form-control'}),
                   'homework': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   'date': forms.NumberInput(attrs={'type': 'date', 'class': 'form-control','max':date.today()}),
                   'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   'teacher': forms.Select(attrs={'class': 'form-control'}),
                   'student': forms.Select(attrs={'class': 'form-control'}),
                   'remark': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),}
        

diaries/views.py
import datetime
from contributions_django.graphs import generate_contributors_graph

from django.shortcuts import render
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from .forms import DiaryForm
from .models import Diary
from users.models import CustomUser


# --------------------------------------------------
# 日報リストの表示
def index(request):
    diary = Diary.objects.all().order_by("date").reverse()
    params = {
        'diaries_list': diary,
    }
    return render(request, 'diaries/index.html', params)

# --------------------------------------------------
# 特定の日報の表示
def detail(request, diary_id):
    diary = Diary.objects.get(pk=diary_id)
    params = {
        'diary': diary,
    }
    return render(request, 'diaries/detail.html', params)

# --------------------------------------------------
# 最新の日報の表示
def new_detail(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    diaries = Diary.objects.filter(student=user).order_by("date").reverse()
    params = {
        'diary': diaries.first(),
    }
    return render(request, 'diaries/detail.html', params)

# --------------------------------------------------
# 日報の作成
def create(request):
    # Submit の処理
    if (request.method == 'POST'):
        diary = DiaryForm(request.POST)
        diary.save()
        return redirect(to='/diaries')

    # 現在の講師ユーザの情報を取得
    teacher = CustomUser.objects.get(id=request.user.id)
    diary_form = DiaryForm(initial={'teacher': teacher})

    # 初期値の設定
    params = {
        'form': diary_form,
    }
    return render(request, 'diaries/create.html', params)

# --------------------------------------------------
# 日報の編集
def edit(request, diary_id):
    obj = Diary.objects.get(id=diary_id)
    
    if (request.method == 'POST'):
        diary = DiaryForm(request.POST, instance=obj)
        diary.save()
        return redirect(to='/diaries')

    params = {
        'id': diary_id,
        'form': DiaryForm(instance=obj)
    }
    return render(request, 'diaries/edit.html', params)

# --------------------------------------------------
#芝生の表示
def heatmap(request):
    dates = Diary.objects.values_list('date', flat=True)
    context = generate_contributors_graph(dates, title="Contributions")
    return render(request, "diaries/heatmap.html", context)

"""
def get(request):
    print("diaryyyyy")

    today = datetime.date.today()
    d = today - datetime.timedelta(days=365)
    data  = []
    for in range(365):
        d += datetime.timedelta(days=1) 
        data.appen({'date': d, 'count': count})

    if request.headers.get("Content-Type") == "application/json":
        diaries = list(Diary.objects.filter(teacher=request.user).values())
        print("diary")
        print(diaries)
        return JsonResponse(diaries, safe=False, status=200)
"""

# --------------------------------------------------
# 日報の削除
@require_POST
def delete(request, diary_id):
    diary = Diary.objects.get(id=diary_id)
    diary.delete()
    return redirect(to='/diaries')

diaries/templates/diaries/create.html
{% extends "base.html" %}

{% block title %}日報の作成{% endblock%}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h1 class="display-6">日報の作成</h1>

  <form action="{% url 'diaries:create' %}" method="post">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {% for item in form %}
    <div class="form-group mb-3">
      
      <!--講師の選択フィールドの未表示-->
      {% if item.label == "Teacher" %}
      <div style="display: none;">
        <label class="mb-1">{{ item.label }}</label>
        {{ item }}
      </div>
      <!--そのほかの入力フィールド-->
      {% else %}
      <label class="mb-1">{{ item.label }}</label>
      {{ item }}
      {% endif %}
      
      {% if field.help_text %}
      <span class="helptext">{{ field.help_text }}</span>
      {% endif %}
      {{ field.errors }}
    </div>
    {% endfor %}

    <div class="text-end">
      <button type="submit" class="btn btn-primary">作成</button>
    </div>
  </form>
</div>
{% endblock %}

diaries/templates/diaries/create_btn.html
<div class="container fixed-bottom mb-3 text-end">
  <a class="btn shadow-lg bg-third text-first" href="{% url 'diaries:create' %}">
    <h3 class="fw-bold"><i class="fa-solid fa-file"></i> 日報を作成</h3>
  </a>
</div>

diaries/templates/diaries/detail.html
{% extends "base.html" %}

{% block title %}
{{ diary.date|date:"n月j日 (D)" }} の日報詳細
{% endblock %}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h2 class="fw-bold">
    <i class="fas fa-book-open" style="color: #6C757D;"></i>
    <span>日報詳細</span>
  </h2>

  <div class="card">
    <!--ヘッダ-->
    <div class="card-header">
      <h4>
        <i class="fas fa-calendar-days" style="color: #6C757D;"></i>
        <span>{{ diary.date|date:"n月j日 (D)" }}</span>
        <span class="badge bg-{{ diary.subject.color }}"> {{ diary.subject }}</span>
      </h4>

      {% if user.job == "teacher" %}
      <!--編集・削除ボタン (右寄せ)-->
      <div class="d-flex justify-content-end">
        <!--横一列-->
        <div class="row g-2">
          <!--編集-->
          <div class="col-auto">
            <a class="btn btn-outline-primary btn-sm" href="{% url 'diaries:edit' diary.id %}" role="button">
              <i class="fas fa-wrench"></i>
            </a>
          </div>
          <!--削除-->
          <div class="col-auto">
            <form method="post" action="{% url 'diaries:delete' diary.id %}">
              {% csrf_token %}
              <button class="btn btn-outline-danger btn-sm" type="submit" onclick='return confirm("日報を削除してよろしいですか？");'>
                <i class="fa-solid fa-trash"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
      {% endif %}
    </div>

    <!--中身-->
    <div class="card-body">
      <h5>
        <p>
          <i class="fas fa-user" style="color: #6C757D;"></i>
          <span>{{ diary.student }}</span>
        </p>
        <p>
          <i class="fas fa-user-tie" style="color: #6C757D;"></i>
          <span>{{ diary.teacher }}</span>
        </p>
      </h5>
      <hr>

      <p class="fs-6 text-secondary">
        <i class="fas fa-clipboard"></i>
        <span>内容</span>
      </p>
      <p class="fs-6">{{ diary.content }}</p>
      <hr>

      <p class="fs-6 text-secondary">
        <i class="fas fa-arrow-up-wide-short"></i>
        <span>担当範囲</span>
      </p>
      <p class="fs-6">{{ diary.range }}</p>
      <hr>

      <p class="fs-6 text-secondary">
        <i class="fas fa-pen"></i>
        <span>宿題</span>
      </p>
      <p class="fs-6">{{ diary.homework }}</p>
      <hr>

      <p class="fs-6 text-secondary">
        <i class="fas fa-message"></i>
        <span>備考</span>
      </p>
      <p class="fs-6">{{ diary.remark }}</p>
    </div>
  </div>
</div>
{% endblock %}

diaries/templates/diaries/edit.html
{% extends "base.html" %}

{% block title %}日報の編集{% endblock %}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h1 class="display-6">日報の編集</h1>

  <form action="{% url 'diaries:edit' id %}" method="post">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {% for item in form %}
    <div class="form-group mb-3">

      <!--講師の選択フィールドの未表示-->
      {% if item.label == "Teacher" %}
      <div style="display: none;">
        <label class="mb-1">{{ item.label }}</label>
        {{ item }}
      </div>
      <!--そのほかの入力フィールド-->
      {% else %}
      <label class="mb-1">{{ item.label }}</label>
      {{ item }}
      {% endif %}

      {% if field.help_text %}
      <span class="helptext">{{ field.help_text }}</span>
      {% endif %}
      {{ field.errors }}
    </div>
    {% endfor %}

    <div class="text-end">
      <button type="submit" class="btn btn-primary">適用</button>
    </div>
  </form>
</div>
{% endblock %}

diaries/templates/diaries/heatmap.html
{% include "contributions_django/graph.html" %}

diaries/templates/diaries/index.html
{% extends "base.html"%}
{% block title %}日報一覧{% endblock %}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h2 class="fw-bold">
    <i class="fas fa-book-open" style="color: #6C757D;"></i>
    <span>日報リスト</span>
  </h2>
  {% include "diaries/list.html" %}
</div>

<!--生徒の場合は出席ボタン-->
{% if user.job == "student" %}
{% include "lessons/create_btn.html" %}
<!--講師の場合は日報作成ボタン-->
{% else %}
{% include "diaries/create_btn.html" %}
{% endif %}
{% endblock %}

diaries/templates/diaries/list.html
{% if diaries_list %}
<div class="d-flex flex-row bd-highlight mb-3 flex-wrap">
  {% for diary in diaries_list %}
  <div class="p-2 bd-highlight w-25">
    <div class="card">
      <div class="card-header">
        <i class="fas fa-calendar-days" style="color: #6C757D;"></i>
        <span>{{ diary.date|date:"n月j日 (D)" }} - {{ diary.student.name }}</span>
        <span class="badge bg-{{diary.subject.color}}"> {{ diary.subject }}</span>
      </div>

      <div class="card-body">
        <p class="fs-6 text-secondary">
          <i class="fas fa-clipboard"></i>
          <span>内容</span>
        </p>

        <p class="fs-6">{{ diary.content }}</p>
        <p class="fs-6 text-secondary">
          <i class="fas fa-pen"></i>
          <span>宿題</span>
        </p>
        
        <p class="fs-6">{{ diary.homework }}</p>
        <div>
          <a class="btn btn-outline-primary" href="{% url 'diaries:detail' diary.id %}">
            <i class="fa-solid fa-magnifying-glass"></i>
            <span>詳細</span>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p>現在、日報はありません。</p>
{% endif %}

diaries/templates/diaries/new_diary.html
{% if new_diary_list and user.id in new_diary_id_list %}
<div>
    {% for diary in new_diary_list %}
    {% if diary.student_id == user.id %}
    <a class="text-decoration-none text-dark" href="{% url 'diaries:new_detail' user.id %}">
        <h6>
            <i class="fas fa-calendar-days" style="color: #6C757D;"></i>
            <span>{{ diary.date|date:"n月j日 (D)" }}</span>
            <span class="badge bg-{{diary.subject.color}}"> {{ diary.subject }}</span>
        </h6>

        <p class="fs-6 text-secondary">
            <i class="fas fa-clipboard"></i>
            <span>内容</span>
        </p>
        <p class="fs-6">{{ diary.content }}</p>
    </a>
    {% endif %}
    {% endfor %}
</div>
{% else %}
<p>最新の日報はありません</p>
{% endif %}