diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:diary_id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('edit/<int:diary_id>', views.edit, name='edit'),
    path('delete/<int:diary_id>', views.delete, name='delete'),
    path('heatmap/', views.heatmap, name='heatmap'),
    path('new/<int:user_id>', views.new_detail, name='new_detail'),
]

jukus/urls.py
from django.urls import path
from . import views

app_name = 'jukus'

urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:record_id>/',views.detail, name='detail'),
    path('chart/',views.chart, name='chart'),
]

team_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('diaries/', include('diaries.urls')),
    path('subjects/', include('subjects.urls')),
    path('records/', include('records.urls')),
    path('lessons/', include('lessons.urls')),
    path('', include('jukus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from records import views as records_views

app_name = 'users'

urlpatterns = [
    path('<int:user_id>/',views.detail, name='detail'),
    path('<int:user_id>/records/',records_views.index, name='records_detail'),
    path('<int:user_id>/follow/',views.follow, name="follow"),
    path('<int:user_id>/following/',views.index, name="following"),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('index/',views.index, name="index"),
    path('<int:user_id>/edit/',views.edit,name="edit"),
    path('teacher_index/',views.teacher_index, name="teacher_index"),
    path('follow_index/', views.follow_index, name="follow_index"),
]

jukus/models.py
from django.db import models

class Juku(models.Model):
    name = models.CharField(("塾名"), max_length=50)
    news = models.CharField(("お知らせ"), max_length=200,null=True)

    def __str__(self):
        return self.name

jukus/views.py
import datetime

from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Juku
from users.models import CustomUser
from users.models import Follow
from diaries.models import Diary

from contributions_django.graphs import generate_contributors_graph
from contributions_django import dateutils

@login_required
def dashboard(request):
    user = request.user
    juku = Juku.objects.get(pk=user.juku_id)

    following = Follow.objects.filter(owner=user)
    following_list = []
    i = 0
    while i < 4 and i < len(following):
        following_list.append(following[i].follow_target)
        i += 1

    dates = Diary.objects.values_list('date', flat=True)
    graph_data = generate_contributors_graph(dates)

    if user.job == "student":
        diaries_list = Diary.objects.filter(student_id=user.id).order_by("date").reverse()[0:4]
    else:
        diaries_list = Diary.objects.all().order_by("date").reverse()[0:4]

    # フォロー生徒の最新の日報の取得
    following_id_list = following.values_list('follow_target_id', flat=True)
    temp_list = []
    new_diary_list = []   
    for id in following_id_list:
        data = Diary.objects.filter(student_id=id).order_by('date').reverse()
        new_diary_list.append(data.first())
        temp_list.append(data.values_list('student_id').first())
        
    new_diary_id_list = []   
    for i in temp_list:
        if (type(i) == type(())):
            new_diary_id_list.append(i[0])
        else: 
            new_diary_id_list.append(i)
        
    params = {
        'juku': juku,
        'user' : user,
        'users_list' : following_list,
        'diaries_list' : diaries_list,
        'contributions_django' : graph_data,
        'month_ago_date' : (datetime.date.today() - datetime.timedelta(30)).strftime("%Y-%m-%d"),
        'new_diary_list': new_diary_list,
        'new_diary_id_list': new_diary_id_list,
    }
    return render(request, 'jukus/dashboard.html', params)

jukus/templates/jukus/custom_graph.html
{% load static %}
{% if contributions_django.include_bootstrap %}<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">{% endif %}
{% if contributions_django.include_fontawesome %}<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">{% endif %}

<style>
.contrib_grad0 {
  background-color: {{ contributions_django.gradients.0 }};
}

.contrib_grad1 {
  background-color: {{ contributions_django.gradients.1 }};
}

.contrib_grad2 {
  background-color: {{ contributions_django.gradients.2 }};
}

.contrib_grad3 {
  background-color: {{ contributions_django.gradients.3 }};
}

.contrib_grad4 {
  background-color: {{ contributions_django.gradients.4 }};
}

/*------------------------------------*\
  # PANEL STYLES
\*------------------------------------*/
.panel {
  margin-left: auto;
  margin-right: auto;
}

.panel-heading {
  font-size: 1.5em;
  font-weight: bold;
  text-align: center;
}

/*------------------------------------*\
  # CELLS
\*------------------------------------*/
.calendar-row {
  display: table;
  border-spacing: 2px 1px;
}

.cell {
  width: 18px;
  height: 18px;
  min-width: 12px;
  min-height: 12px;
  margin: 1px;
  display: table-cell;
  resize: none;
{% if contributions_django.use_circles %}border-radius:30px;{% endif %}
}

.cell:hover {
  border: 1px solid #333;
}

.contrib_empty:hover {
  border: none;
}

.weekday-heading {
  color: #ccc;
  text-align: right;
  font-size: 0.8em;
  padding-right: 3px;
  width: 30px;
}

.month-heading {
  width: 32px;
  font-size: 0.8em;
  text-align: left;
  color: #aaa;
}

.legend {
  margin-top: 16px;
}

/*------------------------------------*\
  # TOOLTIPS
\*------------------------------------*/
.cell {
  position: relative;
  z-index: 24;
}

.cell:hover {
  z-index: 25;
}

.cell span {
  display: none;
}

.cell:hover span {
  width: 255px;
  height: 30px;
  top: -45px;
  left: -110px;
  display: inline-block;
  position: absolute;
  background-color: rgba(1, 1, 1, 0.8);
  color: white;
  text-align: center;
  font-size: 12px;
  border-radius: 4px;
  line-height: 30px;
  vertical-align: middle;
}

.cell:hover span:before {
  border: solid;
  border-color: rgba(1, 1, 1, 0.8) transparent;
  border-width: 7px 7px 0 7px;
  bottom: -7px;
  content: "";
  left: 110px;
  position: absolute;
  z-index: 99;
}

.contrib_empty:hover span {
  display: none;
}


/*------------------------------------*\
  # STATISTICS
\*------------------------------------*/
.statistics.row {
  width: 100%;
}

.col-md-4.middle {
  border-left: 1px solid #ddd;
  border-right: 1px solid #ddd;
}

.annotation {
  color: #aaa;
  margin-bottom: 2px;
}


.big_stat {
  font-size: 2.4em;
  margin-bottom: 5px;
}

</style>

<div class="panel panel-default my-3">
  <div class="panel-body">
    <center>
      <div class="contributions-graph px-1">
        <div class="calendar-row">
          <div class="cell weekday-heading contrib_empty"></div>
          {% for month in contributions_django.months %}
          {% if month %}<div class="cell month-heading contrib_empty">{{ month }}</div>{% else %}<div class="cell contrib_empty"></div>{% endif %}{% endfor %}
        </div>
        {% for row in contributions_django.graph.data %}
        <div class="calendar-row">
          <div class="cell weekday-heading contrib_empty">
            {{ contributions_django.weekdays|last }}
          </div>
          {% for cell in row %}
          <div class="cell contrib_{{ cell.cell_class }}">
            <span>{{ cell.tooltip }}</span>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="calendar-row legend">
          <div class="cell weekday-heading contrib_empty"></div>
          {% for _ in contributions_django.graph.range %}
          <div class="cell contrib_empty"></div>
          {% endfor %}
        </div>
      </div>
  </div>

  <div class="statistics row">
    <div class="col-3 px-5">
      <p class="text-secondary">年間出席日数</p>
      <h2 class="sum">{{ contributions_django.graph.sum }}</h2>
      <p class="annotation">{{ contributions_django.graph.start_date }} &ndash; {{ contributions_django.graph.today_date }}</p>
    </div>
    <div class="col-3 border-start border-2 px-5">
      <p class="text-secondary">月間出席日数</p>
      <h2 class="sum">{{ contributions_django.graph.sum_monthly }}</h2>
      <p class="annotation">{{ month_ago_date }} &ndash; {{ contributions_django.graph.today_date }}</p>
    </div>
    <div class="col-6 px-1 position-relative">
      <div class="position-absolute end-0">
        <div class="cell contrib_empty month-heading">Less</div>
        <div class="cell contrib_empty contrib_grad0"></div>
        <div class="cell contrib_empty contrib_grad1"></div>
        <div class="cell contrib_empty contrib_grad2"></div>
        <div class="cell contrib_empty contrib_grad3"></div>
        <div class="cell contrib_empty contrib_grad4"></div>
        <div class="cell contrib_empty month-heading">&nbsp;More</div>
        <div class="cell contrib_empty"></div>
        <div class="cell contrib_empty"></div>
        <div class="cell contrib_empty"></div>
      </div>
    </div>
  </div>
</div>

jukus/templates/jukus/dashboard.html
{% extends "base.html"%}
{% load static %}

{% block title %}ダッシュボード{% endblock %}

{% block content %}
<div class="px-4 my-4">
  <div class="row">
    <div class="col-3">

      <div class="container bg-light rounded-3 py-3 shadow-lg">
        <div class="container my-3 px-3">
          {% if user.profile_image %}
          <img src="{{ user.profile_image.url }}" class="img-fluid rounded">
          {% else %}
          <img src="../../../media/default/DefaultImage.png" class="img-fluid rounded">
          {% endif %}
        </div>

        <div class="container">
          <h3 class="fw-bold">
            {% if user.job == "student" %}
            <i class="fas fa-user" style="color: #6C757D;"></i>
            {% else %}
            <i class="fas fa-user-tie" style="color: #6C757D;"></i>
            {% endif %}
            <span>{{ user.name }}</span>
          </h3>
        </div>

        <div class="container">
          <p>{{ user.bio }}</p>
        </div>
        <hr>

        <div class="container my-3">
          <i class="fas fa-book" style="color: #6c757d;"></i>
          {% if user.job == "student" %}
          <span class="fs-6 text-secondary">受講科目</span><br>
          {% else %}
          <span class="fs-6 text-secondary">担当教科</span><br>
          {% endif %}

          {% for subjects in user.subjects.all %}
          <span class="badge bg-{{ subjects.color }}">{{ subjects }}</span>
          {% endfor %}
        </div>

        <div class="container my-3">
          <i class="fas fa-school" style="color: #6C757D;"></i>
          <span>{{ user.school }} {{ user.grade }}</span>
        </div>

        <div class="container my-3">
          <a href="{% url 'users:edit' user.id %}" class="btn btn-outline-secondary">
            <i class="fas fa-wrench"></i>プロフィール編集
          </a>
        </div>
        <hr>

        <div class="container my-3">
          バッジとか置く
        </div>
      </div>
    </div>

    <div class="col-9">

      <!--お知らせ-->
      <div class="container bg-light rounded-3 py-3 shadow-lg">
        <h3 class="fw-bold">
          <i class="fas fa-bullhorn" style="color: #6C757D;"></i>
          <span>{{ user.juku }}からのお知らせ</span>
        </h3>
        <div class="alert alert-primary" role="alert">
          {{ juku.news }}
        </div>
      </div>

      <!--担当生徒(講師ユーザの場合のみ表示)-->
      {% if user.job == "teacher" %}
      <div class="container my-4 py-3 bg-light rounded-3">
        <h3 class="fw-bold">
          <a class="text-decoration-none text-third" href="{% url 'users:follow_index' %}">
            <i class="fas fa-users"></i>
            <span>担当生徒</span>
            <span class="vertical-middle fs-6 badge bg-secondary">{{ user.count_following }}</span>
          </a>
        </h3>
        {% include "users/list.html" %}
        <!--<a class="fs-6 text-secondary" href="{% url 'users:following' user.id %}">全ての担当生徒 >></a>-->
      </div>
      {% endif %}

      <!--出席or勤務日数-->
      <div class="container bg-light rounded-3 my-4 py-3 shadow-lg">
        <h3 class="fw-bold">
          <a class="text-decoration-none text-third" href="{% url 'users:index' %}">
            <i class="fa-solid fa-calendar-days"></i>
            {% if user.job == "student" %}
              出席日数
            {% else %}
              勤務日数
            {% endif %}
          </a>
        </h3>
        {% include "jukus/custom_graph.html" %}
      </div>
      

      <!--成績(生徒のみ表示)-->
      {% if user.job == "student" %}
      <div class="container bg-light rounded-3 my-4 py-3 shadow-lg">
        <h3 class="fw-bold">
          <a class="text-decoration-none text-third" href="{% url 'users:records_detail' user.id %}">
            <i class="fa-solid fa-calendar-days"></i> 成績
          </a>
        </h3>
        <div class="row">
          <div class="col-6">
            <h4 class="fw-bold text-secondary" style="text-align:center;">定期テスト</h4>
            <canvas class="records-chart" height="100vh" data-url="{% url 'records:chart' %}" id="定期" ></canvas>
          </div>
          <div class="col-6">
            <h4 class="fw-bold text-secondary" style="text-align:center;">模試</h4>
            <canvas class="records-chart" height="100vh" data-url="{% url 'records:chart' %}" id="模試"></canvas>
          </div>
        </div>
      </div>
      {% endif %}


      <!--最近の日報一覧-->
      <div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
        <h3 class="fw-bold">
          <a class="text-decoration-none text-third" href="{% url 'diaries:index' %}">
            <i class="fas fa-book-open"></i>
            <span>日報</span>
          </a>
        </h3>
        {% include "diaries/list.html" %}
      </div>

      <!--生徒の場合は日報作成ボタン非表示-->
      {% if not user.job == "student" %}
        {% include "diaries/create_btn.html" %}
      {% endif %}
    </div>
  </div>
</div>
<script src="{% static 'chart_ajax.js' %}"></script>

{% endblock %}