jukus/urls.py
from django.urls import path
from . import views

app_name = 'jukus'

urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

team_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('diaries/', include('diaries.urls')),
    path('subjects/', include('subjects.urls')),
    path('records/', include('records.urls')),
    path('lessons/', include('lessons.urls')),
    path('', include('jukus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from records import views as records_views

app_name = 'users'

urlpatterns = [
    path('<int:user_id>/',views.detail, name='detail'),
    path('<int:user_id>/records/',records_views.index, name='records_detail'),
    path('<int:user_id>/follow/',views.follow, name="follow"),
    path('<int:user_id>/following/',views.index, name="following"),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('index/',views.index, name="index"),
    path('<int:user_id>/edit/',views.edit,name="edit"),
    path('teacher_index/',views.teacher_index, name="teacher_index"),
    path('follow_index/', views.follow_index, name="follow_index"),
]

users/models.py
import datetime

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from jukus.models import Juku
from subjects.models import Subject


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Emailを入力して下さい')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('is_staff=Trueである必要があります。')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser=Trueである必要があります。')
        return self._create_user(email, password, **extra_fields)



class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("メールアドレス"), unique=True)
    name = models.CharField(_("氏名"), max_length=50)
    school = models.CharField(_("学校名"), max_length=50)
    bio = models.CharField(_("自己紹介"), max_length=150)
    birthday = models.DateField(_("生年月日"),null=True)
    job = models.CharField(_("講師or生徒"), max_length=20, choices=(('teacher','講師'),('student','生徒'),('manager','管理者')))
    profile_image = models.ImageField(null=True, blank=True)

    juku = models.ForeignKey(Juku, on_delete=models.CASCADE,null=True)
    subjects = models.ManyToManyField(Subject,null=True)

    is_staff = models.BooleanField(_("staff status"), default=False)
    is_active = models.BooleanField(_("active"), default=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.name

    #フォロー人数を表示するfollow関数を定義
    def follow_nums(self):
       return len(Follow.objects.filter(owner=self.id))
    #フォロワー人数を表示するfollower_nums関数を定義
    def follower_nums(self):
       return len(Follow.objects.filter(follow_target=self.id))

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)


    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)


    def count_following(self):
        following = Follow.objects.filter(owner=self)
        following_list = []
        for f in following:
            following_list.append(f.follow_target)

        return len(following_list)


    def grade(self):
        birth_y = self.birthday.year
        birth_m = self.birthday.month
        today_y = datetime.date.today().year

        if birth_m < 4:
            g = today_y - birth_y
        else:           #遅生まれ
            g = today_y - birth_y - 1

        grade = "999"
        if g == 6:
            grade = "小学1年生"
        elif g == 7:
            grade = "小学2年生"
        elif g == 8:
          grade = "小学3年生"
        elif g == 9:
            grade = "小学4年生"
        elif g == 10:
            grade = "小学5年生"
        elif g == 11:
            grade = "小学6年生"
        elif g == 12:
            grade = "中学1年生"
        elif g == 13:
            grade = "中学2年生"
        elif g == 14:
            grade = "中学3年生"
        elif g == 15:
            grade = "高校1年生"
        elif g == 16:
            grade = "高校2年生"
        elif g == 17:
            grade = "高校3年生"

        return grade


class Follow(models.Model):
    owner = models.ForeignKey(
       CustomUser,
       on_delete=models.CASCADE,
       related_name = 'do_follow_user'
   )
    follow_target = models.ForeignKey(
       CustomUser,
       on_delete=models.CASCADE,
       related_name = 'accept_follow_user'
   )

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from users.models import CustomUser

# --------------------------------------------------
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
        
# --------------------------------------------------
# Eメールを用いた認証の実装
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = {'email', "name", "school", "birthday", 'job', 'juku','bio','profile_image','subjects'}
        widgets = {
            'birthday': forms.SelectDateWidget
        }

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .models import CustomUser, Follow
from diaries.models import Diary
from . import forms

def index(request):
    users = CustomUser.objects.filter(job="student")
    users_id_list = users.values_list('id', flat=True)
    
    temp_list = []
    new_diary_list = []   
    for id in users_id_list:
        data = Diary.objects.filter(student_id=id).order_by('date').reverse()
        new_diary_list.append(data.first())
        temp_list.append(data.values_list('student_id').first())
    
    new_diary_id_list = []   
    for i in temp_list:
        if (type(i) == type(())):
            new_diary_id_list.append(i[0])
        else: 
            new_diary_id_list.append(i)
            
    params = {
        'title': '生徒',
        'users_list': users,
        'new_diary_list': new_diary_list,
        'new_diary_id_list': new_diary_id_list,
    }
    return render(request, 'users/index.html', params)

def teacher_index(request):
    users = CustomUser.objects.filter(job="teacher")
    params = {
        'title': '講師',
        'users_list': users,
    }
    return render(request, 'users/index.html', params)

def follow_index(request):
    # フォロー中の生徒を取得
    follows_id_list = Follow.objects.filter(owner=request.user).values('follow_target_id').values_list('follow_target_id', flat=True)
    users = CustomUser.objects.filter(id__in=follows_id_list)
    
    temp_list = []
    new_diary_list = []   
    for id in follows_id_list:
        data = Diary.objects.filter(student_id=id).order_by('date').reverse()
        new_diary_list.append(data.first())
        temp_list.append(data.values_list('student_id').first())
        
    new_diary_id_list = []   
    for i in temp_list:
        if (type(i) == type(())):
            new_diary_id_list.append(i[0])
        else: 
            new_diary_id_list.append(i)
        
    params = {
        'title': '担当生徒',
        'users_list': users,
        'new_diary_list': new_diary_list,
        'new_diary_id_list': new_diary_id_list,
    }
    return render(request, 'users/index.html', params)

def detail(request, user_id):
    user = CustomUser.objects.get(pk=user_id)
    diaries = Diary.objects.filter(student = user)
    birthday = user.birthday
    params = {
        'user': user,
        'diaries_list': diaries,
    }
    return render(request, 'users/detail.html', params)

def follow(request, user_id):
    following = CustomUser.objects.get(pk=user_id)
    Follow.objects.get_or_create(owner=request.user, follow_target=following)
    return HttpResponseRedirect(reverse('users:detail', args=[str(user_id)]))

def edit(request,user_id):
    obj=CustomUser.objects.get(id=user_id)

    if (request.method == 'POST'):
        user = forms.CustomUserCreationForm(request.POST,instance=obj)
        if user.is_valid():
            user.save()
            return redirect(to='/users/index')
        else:
            print("valid failed")

    params = {
        'id': user_id,
        'form': forms.CustomUserCreationForm(instance=obj)
    }
    return render(request,'users/edit.html',params)

class MyLoginView(LoginView):
    form_class = forms.LoginForm
    template_name = "users/login.html"

class MyLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "users/logout.html"

users/templates/users/create.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>ユーザ作成</title>
</head>

<body>
    <h1>新規ユーザの作成</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">作成</button>
    </form>
</body>

</html>

users/templates/users/detail.html
{% extends "base.html"%}
{% block title %}{{ user.name }} の詳細{% endblock %}

{% block content %}
<div class="container bg-light rounded-3 my-4 py-4 shadow-lg">
  <div class="container bg-light border-bottom px-4">
    <div class="row">
      <div class="col-4 p-4">
        {% if user.profile_image %}
        <img src="{{ user.profile_image.url }}" class="img-fluid rounded">
        {% else %}
        <img src="../../../media/default/DefaultImage.png" class="img-fluid rounded">
        {% endif %}
      </div>

      <div class="col-8 p-4">
        <h1 class="fw-bold">
          {% if user.job == "student" %}
          <i class="fas fa-user" style="color: #6C757D;"></i>
          {% else %}
          <i class="fas fa-user-tie" style="color: #6C757D;"></i>
          {% endif %}
          <span>{{ user.name }}</span>
        </h1>
        <h5 class="text-muted fw-normal">
          <i class="fas fa-school" style="color: #6C757D;"></i>
          <span>{{ user.school }}</span>
        </h5>

        <h5 class="text-muted fw-normal">
          <i class="fas fa-address-card" style="color: #6C757D;"></i>
          <span>{{ user.grade }}</span>
        </h5>
        <br>

        <p class="fs-4 text-secondary">
          <i class="fas fa-paperclip" style="color: #6C757D;"></i>
          {% if user.job == "student" %}
          受講科目
          {% else %}
          担当教科
          {% endif %}
        </p>
        {% for subjects in user.subjects.all %}
        <span class="mb-1 fs-6 badge bg-{{ subjects.color }}">{{subjects}}</span>
        {% endfor %}
      </div>
    </div>
  </div>

  {% if user.job == "student" %}
  <div class="container  border-bottom pb-4 my-4">
    <h2 class="pb-3">
      <i class="fas fa-book-open" style="color: #6C757D;"></i>
      <span>日報</span>
    </h2>
    {% include "diaries/list.html" %}
  </div>
  <div class="container">
    <h2 class="fw-bold">
      <a class="text-decoration-none text-success" href="{% url 'users:records_detail' user.id %}">
        <i class="fas fa-chart-column"></i>
        <span>成績詳細</span>
      </a>
    </h2>
  </div>
  {% else %}
  {% endif %}
  {% endblock %}

users/templates/users/edit.html
{% extends "base.html" %}

{% block title %}プロフィールの編集{% endblock %}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h1 class="display-6">プロフィールの編集</h1>

  <form action="{% url 'users:edit' id %}" method="post">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {% for item in form %}
    <div class="form-group mb-3">
      <div>
        <label class="mb-1">{{ item.label }}</label>
        {{ item }}
      </div>
      {% if field.help_text %}
      <span class="helptext">{{ field.help_text }}</span>
      {% endif %}
      {{ field.errors }}
    </div>
    {% endfor %}

    <div class="text-end">
      <button type="submit" class="btn btn-primary">適用</button>
    </div>
  </form>
</div>
{% endblock %}

users/templates/users/index.html
{% extends "base.html" %}
{% block title %}{{ title }}一覧{% endblock %}

{% block content %}
<div class="container my-4 py-3 bg-light rounded-3 shadow-lg">
  <h2 class="fw-bold">
    <i class="fas fa-users" style="color: #6C757D;"></i>
    <span>{{ title }}一覧</span>
  </h2>
  {% include "users/list.html" %}
</div>
{% endblock%}

users/templates/users/list.html
{% if users_list %}
<div class="d-flex flex-row bd-highlight mb-3 flex-wrap">
  {% for user in users_list %}
  <div class="p-2 bd-highlight w-25">
    <div class="container rounded-3 border bg-white py-2">
      <div class="row">

        <div class="col-5">
          {% if user.profile_image %}
          <img src="{{user.profile_image.url }}" class="img-fluid rounded">
          {% else %}
          <img src="../../../media/default/DefaultImage.png" class="img-fluid rounded">
          {% endif %}
        </div>

        <div class="col-7 py-3 px-1">
          <h5 class="fw-bold">
            <a class="text-decoration-none text-dark" href="{% url 'users:detail' user.id %}">
              <i class="fas fa-user" style="color: #6C757D;"></i>
              <span>{{ user.name }}</span>
            </a>
          </h5>
          <i class="fas fa-school" style="color: #6C757D;"></i>
          <span class="text-secondary">{{ user.school }}</span>
          <br>
          {% for subjects in user.subjects.all %}
          <span class="badge bg-{{subjects.color}}">{{subjects}}</span>
          {% endfor %}
        </div>
      </div>

      <!--<p>
        <a class="btn btn-outline-primary" href="{% url 'users:follow' user.id %}">フォロー</a>
      </p>-->

      <h6 class="fw-bold">
        <i class="fas fa-book-open" style="color: #6C757D;"></i>
        <span>最新の日報</span>
      </h6>
      <div class="container bg-light rounded-3 pt-3 pb-1">
        {% include "diaries/new_diary.html" %}
      </div>

      <hr>
      簡単な成績出したい
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No Users</p>
{% endif %}

users/templates/users/login.html
<!doctype html>
{% load django_bootstrap5 %}
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>ログイン画面 | Proglesson</title>
  <link href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
  <style>
    .bg-gradient {
      background-color: #3ff471;
      background-image: linear-gradient(132deg, #3ff471 0%, #16A085 100%);
    }

    .bg-first {
      background-color: #f6f6f6;
    }

    .bg-second {
      background-color: #d6e4f0;
    }

    .bg-third {
      background-color: #1e56a0
    }

    .bg-fourth {
      background-color: #163172;
    }

    .text-first {
      color: #f6f6f6;
    }

    .text-second {
      color: #d6e4f0;
    }

    .text-third {
      color: #1e56a0
    }

    .text-fourth {
      color: #163172;
    }

    .full {
      min-height: 100vh;
    }

    .logo {
      color: white !important;
      height: 3em !important;
    }

    .vertical-middle {
      background: yellow;
      display: inline-block;
      vertical-align: middle;
    }

    .form-signin {
      width: 100%;
      max-width: 330px;
      padding: 15px;
      margin: auto;
    }

    .form-signin .form-floating:focus-within {
      z-index: 2;
    }

    .form-signin input[type="text"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
  </style>
</head>

<body>
  <div class="m-0 py-2 bg-second full">
    <div class="container bg-light rounded-3 mt-5 py-4 shadow-lg">
      <div class="text-center mt-3">
        <img src="/media/Proglesson_blue.svg" class="logo px-3">
        <!--
        <div class="bg-third rounded-3" style="display:inline-block">
          <img src="/media/Proglesson.svg" class="logo px-3 my-3">
        </div>-->
      </div>
      <h1 class="fw-bold text-dark text-center pt-3">ログイン</h1>

      <!--入力エラーメッセージ表示-->
      <main class="form-signin">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endfor %}
        {% endif %}

        <!--入力部分-->
        <form method="POST">
          {% csrf_token %}
          {% for item in form %}
          <div class="form-floating">
            <input type="{{ item.field.widget.input_type }}" class="form-control" name="{{ item.name }}"
              id="{{ item.id_for_label }}" placeholder="xxxxx">
            <label for="{{ item.id_for_label }}">
              <i class="fas fa-{% cycle 'envelope' 'key' %}"></i>
              <span>{{ item.label }}</span>
            </label>
          </div>
          {% endfor %}

          <button type="submit" class="btn btn-primary btn-lg w-100 mt-4">ログイン</button>
        </form>
      </main>
    </div>
  </div>
</body>