jukus/urls.py
from django.urls import path
from . import views

app_name = 'jukus'

urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

team_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('diaries/', include('diaries.urls')),
    path('subjects/', include('subjects.urls')),
    path('records/', include('records.urls')),
    path('lessons/', include('lessons.urls')),
    path('', include('jukus.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from records import views as records_views

app_name = 'users'

urlpatterns = [
    path('<int:user_id>/',views.detail, name='detail'),
    path('<int:user_id>/records/',records_views.index, name='records_detail'),
    path('<int:user_id>/follow/',views.follow, name="follow"),
    path('<int:user_id>/following/',views.index, name="following"),
    path('login/', views.MyLoginView.as_view(), name="login"),
    path('logout/', views.MyLogoutView.as_view(), name="logout"),
    path('index/',views.index, name="index"),
    path('<int:user_id>/edit/',views.edit,name="edit"),
    path('teacher_index/',views.teacher_index, name="teacher_index"),
    path('follow_index/', views.follow_index, name="follow_index"),
]

templates/base.html
<!doctype html>
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load static %}
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<title>{% block title %}{% endblock %}</title>
	<link href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<style>
		.bg-gradient {
			background-color: #3ff471;
			background-image: linear-gradient(132deg, #3ff471 0%, #16A085 100%);
		}
    .bg-first {
      background-color: #f6f6f6;
    }
    .bg-second{
      background-color: #d6e4f0;
    }
    .bg-third {
      background-color: #1e56a0
    }
    .bg-fourth {
      background-color: #163172;
    }
    .text-first {
      color: #f6f6f6;
    }
    .text-second{
      color: #d6e4f0;
    }
    .text-third {
      color: #1e56a0
    }
    .text-fourth {
      color: #163172;
    }
    .full {
        min-height: 100vh;
    }
    .logo {
      color: white !important;
      height: 3em !important;
    }
    .vertical-middle{
      background: yellow; 
      display: inline-block; 
      vertical-align: middle; 
    }

	</style>

</head>

<body>
  <div class="px-3 py-2 bg-third shadow-lg">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center text-white my-2 my-lg-0 me-lg-auto text-decoration-none">
            <img src="/media/Proglesson.svg" class="logo">
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="{% url 'jukus:dashboard' %}" class="nav-link text-white">
                {% bs_icon 'speedometer2' size='1.5em' extra_classes='bi d-block mx-auto mb-1' %}
                ホーム
              </a>
            </li>
            <li>
              <a href="{% url 'users:index' %}" class="nav-link text-white">
                {% bs_icon 'people-fill' size='1.5em' extra_classes='bi d-block mx-auto mb-1' %}
                生徒
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                {% bs_icon 'gear-wide-connected' size='1.5em' extra_classes='bi d-block mx-auto mb-1' %}
                設定
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
	<div class="m-0 py-2 bg-second full">
		{% block content %}{% endblock %}
	</div>

</body>
</html>